### ISSUE TITLE
CocoaPods integration

### ISSUE THREAD

**Issue by josete89** [jduquennoy/Log4swift#3] opened 2015-10-26 07:52 UTC
I added Log4swift in my project using cocoapods and throw me this errors when is building the project:

MyProject/Pods/Log4swift/Log4swift/log4swift.h:32:9: error: include of non-modular header inside framework module 'Log4swift.log4swift'
# import <Log4swift/NSLogger.h>

MyProject/Pods/Log4swift/Log4swift/log4swift.h:33:9: error: include of non-modular header inside framework module 'Log4swift.log4swift'
# import <Log4swift/LoggerClient.h>

MyProject/Pods/Log4swift/Log4swift/log4swift.h:34:9: error: include of non-modular header inside framework module 'Log4swift.log4swift'
# import <Log4swift/LoggerCommon.h>

MYProject/Pods/Log4swift/Log4swift/log4swift.h:36:9: error: include of non-modular header inside framework module 'Log4swift.log4swift'
# import <Log4swift/ASLWrapper.h>

<unknown>:0: error: could not build Objective-C module 'Log4swift'

**Comment by jduquennoy** [comment] 2015-10-26 11:37
Hi josete89,

I'm trying to reproduce the problem using a swift project, Xcode 7.0, cocoapods v0.39.0 this podfile : 

```
platform :osx, '10.10'
pod 'Log4swift', '1.0.0b3'
use_frameworks!
```

It is working without an error.
Can you post the podfile you have ?

**Comment by josete89** [comment] 2015-10-26 11:40
platform :ios, '8.0'
use_frameworks!

target 'MyTarget' do

```
pod 'CWStatusBarNotification'
pod 'Socket.IO-Client-Swift' , '~> 3.0.1'
pod 'SwiftLoader', :git => 'https://github.com/leoru/SwiftLoader'
pod 'EasyAnimation' , '~> 1.0.1'
#pod 'RxSwift', '~> 2.0.0-alpha'
#pod 'RxCocoa', '~> 2.0.0-alpha'
#pod 'RxBlocking', '~> 2.0.0-alpha'
pod 'RealmSwift', '~> 0.95'
pod 'Log4swift', '1.0.0b3'
pod 'ReachabilitySwift', '~> 2.0'
pod 'Fabric', '~> 1.5'
pod 'Crashlytics'
```

end

cocoapods ->  0.39.0

**Comment by jduquennoy** [comment] 2015-10-26 13:52
Hum ... that is strange : I created a brand new swift project targeting iOS, pasted your PodFile, run pod install, and it compiles perfectly.

I can see multiple discussions about that, including this one : http://stackoverflow.com/questions/24103169/swift-compiler-error-non-modular-header-inside-framework-module
One of the proposed solutions is to add that to the PodFile :

```
post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end
```

That would be strange, as it is not required on my side, but it might help understanding where the problem is.

**Comment by josete89** [comment] 2015-10-26 21:17
What Xcode are you using? It seems Xcode bug!

**Comment by jduquennoy** [comment] 2015-10-27 08:30
I did the sample project on Xcode v7.0 (7A218)

**Comment by josete89** [comment] 2015-10-27 09:59
I'm using Version 7.1 (7B91b) ,it seem this bug fixed in 7.0 but comes back in 7.1 ... I added the code in PodFile and didn't work I'm still finding a solution

**Comment by josete89** [comment] 2015-10-27 10:00
CocoaPods issue -> https://github.com/CocoaPods/CocoaPods/issues/3767

**Comment by jduquennoy** [comment] 2015-10-27 10:08
Ok.
Maybe I should close this issue then, if you agree with it.
Thanks for the link !

**Comment by josete89** [comment] 2015-10-27 10:16
Yes you can close the issue!

**Closed as completed** 2015-10-27 10:38 UTC
